# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Include:
    - "**/*"

Bundler/DuplicatedGem:
  Enabled: true

Bundler/DuplicatedGroup:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true
